name: CI - Build and Test

on:
  push:
    branches: [ main, master, develop, feature/* ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: |
        if npm run lint --silent 2>/dev/null; then
          npm run lint
        else
          echo "No lint script found, skipping linting"
        fi
        
    - name: Run type checking
      run: |
        if npm run typecheck --silent 2>/dev/null; then
          npm run typecheck
        elif npx tsc --version >/dev/null 2>&1; then
          npx tsc --noEmit
        else
          echo "No TypeScript checking available, skipping"
        fi
        
    - name: Run tests
      run: |
        if npm run test --silent 2>/dev/null; then
          npm run test -- --coverage --watchAll=false
        else
          echo "No test script found, skipping tests"
        fi
        
    - name: Build project
      run: |
        if npm run build --silent 2>/dev/null; then
          npm run build
        else
          echo "No build script found, attempting Expo build"
          if npx expo --version >/dev/null 2>&1; then
            npx expo export --platform web
          else
            echo "No build process available"
          fi
        fi
        
    - name: Upload test coverage
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30
        if-no-files-found: ignore
        
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          dist/
          .expo/
          build/
        retention-days: 7
        if-no-files-found: ignore